intentionally harmful ecosystems
intarchboard/draft-protocol-maintenance pull request #54
Opened 2022-11-16 22:42 UTC by hardaker

intentionally harmful ecosystems

2022-11-16 23:13 UTC, martinthomson requested changes
We need to be careful here.

The GSS API example is probably a good one to demonstrate market capture, both because it is clearly abuse of market dominance and because the time has long passed.

However, I think that we should avoid dumping on a single vendor for abuses.  Microsoft were also at fault with HTML.  The use of "embrace and extend" (which was "embrace and extinguish") probably goes too far though.  We can point to the risks without laying it all at their feet so directly.

Are you aware of any good citations for SQL?

(I want to come back to this and turn this into two or three paragraphs.  One to lay out the market dominance risks and then some examples.)

2022-11-16 23:13 UTC, martinthomson commented on draft-iab-protocol-maintenance.md
> +## Intentionally harmful ecosystems
```suggestion
## Vendor Capture
```

2022-11-16 23:13 UTC, martinthomson commented on draft-iab-protocol-maintenance.md
> +GSS API {{?GSS=RFC1964}}. [TODO: need to the RFC that microsoft's
RFC 4121 ?

2022-11-22 14:41 UTC, hardaker commented on draft-iab-protocol-maintenance.md
> +GSS API {{?GSS=RFC1964}}. [TODO: need to the RFC that microsoft's
Probably 4121 yes.

2022-11-22 14:45 UTC, hardaker commented
That's a good point about not picking on a single vendor.  I wasn't trying to, and never actually spelled out who the vendor was in my proposed text, but it was [indeed] pointing toward a single one coincidentally.

Another issue to maybe highlight is the large gorillas that have blocked forward progress in interoperability to ensure vertical monopolies with their products.  Routing vendors, OS vendors, web browsers, etc have all played these games often even cooperating to ensure that all sides would not interoperate even when it might be best for the user.

2022-11-22 15:04 UTC, hardaker commented
as for sql references -- nothing fantastic that I can think of.  Some not-great references:

https://en.wikibooks.org/wiki/SQL_Dialects_Reference/Introduction

https://www.quora.com/Why-are-there-so-many-types-of-SQL-What-is-the-difference-between-all-of-them?share=1

https://en.wikipedia.org/wiki/SQL#Reasons_for_incompatibility

2022-12-01 23:12 UTC, DavidSchinazi requested changes
I see the historical value of this paragraph, but it doesn't provide guidance. One way to summarize it is "some people were evil in the past and it sucked" but as a reader there's no real guidance. Advice along the lines of "don't be evil" won't be heeded by those who are doing harm intentionally. Given the risk of folks feeling singled out, I'd suggest avoiding this.

2022-12-02 11:13 UTC, martinthomson commented
This PR extends the scope, albeit only a tiny bit, in a new direction.  That is, we aren't really talking about intentionally subverting the process by which a community defines what a protocol is, but more the adverse effects that come from neglect and casual abuse.  

That is, rather than engage with what is a rather tricky topic, we can call this one done.  (Not saying it isn't a problem, but maybe we can avoid making it *our* problem.)

2022-12-02 11:13 UTC, closed without merging