better describe the TLS situation
intarchboard/draft-protocol-maintenance pull request #58
Opened 2022-11-16 22:42 UTC by hardaker

better describe the TLS situation

2022-11-16 23:29 UTC, martinthomson requested changes

2022-11-16 23:29 UTC, martinthomson commented on draft-iab-protocol-maintenance.md
> +become a new undocumented implementation requirement.
This might be your central point, but you can probably do the same with the tweak I suggest above.

2022-11-16 23:29 UTC, martinthomson commented on draft-iab-protocol-maintenance.md
> +implementation quickly.
I don't think that this works, unfortunately.  Empty TLS extensions weren't needed - or at least, not in the problematic position - until the bug was well-entrenched.

2022-11-16 23:29 UTC, martinthomson commented on draft-iab-protocol-maintenance.md
>  with an empty extension. To maintain interoperability, client implementations
```suggestion
with an empty extension. To maintain interoperability with these servers,
which were widely deployed, client implementations
```

2022-12-01 23:02 UTC, DavidSchinazi requested changes
I like the first part of this PR, see details inline.

2022-12-02 20:30 UTC, closed without merging